development:
  adapter: mysql2
  encoding: utf8
  database: refac3
  username: root
  password: darkness
  host: localhost
test:
  adapter: mysql2
  encoding: utf8
  database: refac3
  username: root
  password: darkness
  host: localhost
production:
  adapter: mysql2
  encoding: utf8
  database: refac3
  username: root
  password: darkness
  host: localhost